# Generated by Django 4.2.11 on 2024-03-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenk',
            unique_together={('cik', 'filing_date')},
        ),
    ]
